# Generated by Django 2.2.24 on 2022-03-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('title_book', models.CharField(max_length=100, verbose_name='Title')),
                ('image_book', models.ImageField(null=True, upload_to='images/', verbose_name='Image')),
                ('description_book', models.TextField(null=True, verbose_name='Description')),
            ],
        ),
    ]
